version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro #sincs container to local drive
      - /app/node_modules #annonymous volume
    environment:
      - NODE_ENV=development
      - MONGO_USER=phil
      - MONGO_PASSWORD=pass

    command: npm run dev
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: phil
      MONGO_INITDB_ROOT_PASSWORD: pass