version : "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: phil
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongo-db:/data/db
  
  redis:
    image: redis
    

volumes:
  mongo-db:
